# Generated by Django 3.1 on 2020-11-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialPosts', '0002_auto_20201111_1401'),
        ('socialComments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcomments',
            name='post',
        ),
        migrations.AddField(
            model_name='socialcomments',
            name='from_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='socialPosts.socialpost'),
        ),
    ]
