# Generated by Django 3.1 on 2020-11-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialComments', '0002_auto_20201111_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialcomments',
            old_name='from_post',
            new_name='at_post',
        ),
    ]
